# Generated by Django 4.1.5 on 2023-01-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=65000)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('resume', models.CharField(max_length=60000)),
                ('date_de_publication', models.CharField(max_length=200)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.auteur')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.genre')),
            ],
        ),
    ]
