# Generated by Django 4.1.5 on 2023-01-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_remove_auteur_id_alter_auteur_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livreauteur', to='bibliotheque.auteur'),
        ),
    ]
